version: '3'

services:

  db:
    container_name: ouro-db
    build:
        context: database
        dockerfile: Dockerfile
    ports:
      - "3308:3306"
    env_file:
      - .env
    networks:
      - ouro-bot
    volumes:
      - ./docker/database/dbdata:/var/lib/mysql

networks:
  ouro-bot:
